server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: auth-service-route
          uri: https://yelling-robyn-ietdavv-e7f0666f.koyeb.app
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        - id: customer-service-route
          uri: https://married-reeba-ietdavv-c85073b0.koyeb.app
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1

        - id: accounts-service-route
          uri: https://shiny-karilynn-mpdc-d5efad70.koyeb.app
          predicates:
            - Path=/accounts-service/**
          filters:
            - StripPrefix=1

        - id: payment-service-route
          uri: https://entire-rozanna-mpdc-315742bb.koyeb.app
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1

        - id: notification-service-route
          uri: https://varying-cyndie-mpdc-f3bd695f.koyeb.app
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1

# ðŸ‘‡ CORS wala section yahan se delete kar diya hai kyunki CorsConfig.java ab handle karega

eureka:
  client:
    service-url:
      defaultZone: https://broken-regine-ietdavv-9ba71a3f.koyeb.app/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG