server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Auto-discovery band rakha hai stable routing ke liye

      routes:
        # --- Auth Service ---
        - id: auth-service-route
          uri: https://yelling-robyn-ietdavv-e7f0666f.koyeb.app
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        # --- Customer Service ---
        - id: customer-service-route
          uri: https://married-reeba-ietdavv-c85073b0.koyeb.app
          predicates:
            - Path=/customer-service/**
          filters:
            - StripPrefix=1

        # --- Accounts Service ---
        - id: accounts-service-route
          uri: https://shiny-karilynn-mpdc-d5efad70.koyeb.app
          predicates:
            - Path=/accounts-service/**
          filters:
            - StripPrefix=1

        # --- Payment Service ---
        - id: payment-service-route
          uri: https://entire-rozanna-mpdc-315742bb.koyeb.app
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1

        # --- Notification Service ---
        - id: notification-service-route
          uri: https://varying-cyndie-mpdc-f3bd695f.koyeb.app
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1

      # CORS Fix: OPTIONS request ko Gateway level par hi handle karne ke liye
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      # Isme humne teri Eureka Registry ki link daal di hai
      defaultZone: https://broken-regine-ietdavv-9ba71a3f.koyeb.app/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG